apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    adhoc: narutoq3
  name: q3svcnaruto
spec:
  ports:
  - port: 30021
    protocol: TCP
    targetPort: 30021
  selector:
    adhoc: narutoq3
  type: NodePort
status:
  loadBalancer: {}
