apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web1
  name: adhocrcnaruto4
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    adhoc: narutorcq4
  type: LoadBalancer
status:
  loadBalancer: {}
