apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    adhoc: narutoq2 
  name: adhocpod1
spec:
  containers:
  - image: nginx
    name: adhocpod1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

