apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    adhoc: narutoq2
  name: q2svcnaruto
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    adhoc: narutoq2
  type: NodePort
status:
  loadBalancer: {}

